### ISSUE TITLE
Diseño del mockup

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-buscadores-de-datos#2]
https://www.figma.com/proto/HD0IxARtsByypvfbXvhSex/Reinscripci%C3%B3n?page-id=0%3A1&type=design&node-id=27-10&viewport=794%2C378%2C0.31&t=FidRfFTx0vihKmcY-1&scaling=min-zoom&starting-point-node-id=2%3A2&mode=design

Integrantes del equipo
* Ariadna Monserrat López Aparicio
*  Roldan Uriel Arcadio Avila 
* Pedro Garcia Garcia

[REPORTE DEL MOCKUP.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-buscadores-de-datos/files/14173270/REPORTE.DEL.MOCKUP.pdf)

**Comment by Anakimberly** [comment]
95/100 debido a que tiene faltas de ortografía y su conclusión es menor a 12 renglones

**Comment by josealfredo79** [comment]
solo falta aplicar la regla 3 por favor para asignar...

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
